functions01:
  restart: always
  image: treeder/functions
functions02:
  restart: always
  image: treeder/functions
functions03:
  restart: always
  image: treeder/functions
caddy:
  image: abiosoft/caddy
  volumes:
    - ./Caddyfile:/etc/Caddyfile
  ports:
    - "9000:9000"
  environment:
    - LB_HOST01=functions01:8080
    - LB_HOST02=functions02:8080
    - LB_HOST03=functions03:8080
  links:  
   - functions01
   - functions02
   - functions03